steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}", "."]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${PROJECT_ID}:${_SQL_REGION}:${_SQL_INSTANCE_NAME}",
        "-e",
        "FLASK_APP=controller_app.py",
        "-e",
        "DATABASE_URI=${_CLOUD_DB_URI}",
        "--",
        "python",
        "-m",
        "flask",
        "db",
        "upgrade",
      ]

  - id: "sow seeds"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${PROJECT_ID}:${_SQL_REGION}:${_SQL_INSTANCE_NAME}",
        "-e",
        "FLASK_APP=controller_app.py",
        "-e",
        "DATABASE_URI=${_CLOUD_DB_URI}",
        "--",
        "python",
        "-m",
        "flask",
        "db-seeds",
      ]

substitutions:
  _CLOUD_DB_URI:
  _SQL_INSTANCE_NAME:
  _SQL_REGION:
  _SERVICE_NAME: crmintapp-db-migrations

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
