name: testing-cli
on:
  workflow_dispatch:

  push:
    paths-ignore:
      - 'README.md'
jobs:
  run-cli-tests:
    runs-on: ubuntu-18.04
    steps:
      # Checkout repository code
      - uses: actions/checkout@v2
      # Configure python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # Setup the CRMint test environment
      - name: Setup CLI
        run: pip install ./cli[test]
      # Run the tests
      - name: Run the tests
        working-directory: cli
        run: pytest --cov=. --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          working-directory: cli
          fail_ci_if_error: false
          flags: cli
